name: Approve PR

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  approve-pr:
    runs-on: ubuntu-latest
    steps:
      - name: submit-review
        id: review-api-request
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"commit_id": "${{ github.event.pull_request.head.sha }}", "body": "this is good", "event": "APPROVE"}' \
          https://api.github.com/repos/aegis1k/workflow-approve-test/pulls/${{ github.event.pull_request.number }}/reviews
      - name: merge
        id: merge-api-request
        run: |
          curl -X PUT \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"commit_title":"Merge from actions,"commit_message":"testing merge from actions"}' \
          https://api.github.com/repos/aegis1k/workflow-approve-test/pulls/${{ github.event.pull_request.number }}/merge
